const express = require('express')
const goodsHander = require('../router_handler/goods')
const expressJoi = require('@escook/express-joi')
const { goods_class_schema} = require('../schema/goods')
const { goods_item_schema} = require('../schema/goods')
const { slide_name_schema} = require('../schema/goods')
const router = express.Router()
router.get('/homegoods/:goods_class/:goods_item_title', goodsHander.getHomeGoods)
router.get('/homegoodstitle/:goods_class', goodsHander.getHomeGoodsTitle)
router.get('/imgurl/:goods_class', goodsHander.getHomeGoodsImg)
router.get('/slidelist/:product_id', goodsHander.getSlideList)
router.get('/detail/:product_id', goodsHander.getDetail)
router.get('/editions/:product_id', goodsHander.getEditions)
router.get('/colors/:product_id', goodsHander.getColors)
router.get('/sale/:s_edition/:s_name', goodsHander.getPrice)
router.get('/service/:product_id/:s_type', goodsHander.getServiceList)
router.get('/serviceType/:product_id', goodsHander.getServiceType)
router.get('/checkedService/:price/:name', goodsHander.getCheckMiServiceList)
// 路径一定要用英文
module.exports=router